### ISSUE TITLE
write unit tests for the query interface app

### ISSUE THREAD

**Issue by surchs** [neurobagel/concept_query#86]
we want to have unit test coverage of the core methods we wrote for the demo. This includes

- [ ] the query generator
- [ ] the query view function
- [ ] database caching for query responses
- [ ] api calls for the actual stardog graph
